import type { Metadata } from "next";
import { Geist_Mono, Playfair_Display, Oswald } from "next/font/google";
import "./globals.css";

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
});

const oswald = Oswald({
  subsets: ['latin'],
  variable: '--font-oswald',
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${oswald.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
